spring:
  application:
    name: ProjectUsingAllOfToolsTest
  profiles:
    active: dev

server:
  port: 8080

language-mapping:
  ARABIC:
    - UAE
    - SAUDI_ARABIA
    - QATAR
  ENGLISH:
    - USA
    - UK
    - FRANCE
    - AZERBAIJAN


