spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: vendo
    password: vendo-test
    url: jdbc:postgresql://localhost:5432/Vendo-test
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
    show-sql: false

